"""followers

Revision ID: 22347abf6421
Revises: 8b4955f4bfc4
Create Date: 2018-09-28 14:12:50.219053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22347abf6421'
down_revision = '8b4955f4bfc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
